

services:
  php:
    build: .
    ports:
      - "8080:80"  # Mapea el puerto 80 del contenedor al puerto 8080 del host
    volumes:
      - .:/var/www/html  # Monta el código fuente en el contenedor
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

