name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main # Puedes cambiar esto a la rama que quieras usar para desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # Login en Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      # Construcción y push de la imagen Docker
      - name: Build, tag, and push Docker image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          IMAGE_TAG=latest
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      # Desplegar en ECS
      - name: Deploy to Amazon ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ECS_CLUSTER_NAME="microservices-test"
          SERVICE_NAME="microservicios"
          TASK_FAMILY="microservices-notification"  # El nombre de la familia de la task definition
          ECR_IMAGE_URI="${{ secrets.ECR_REPOSITORY }}:latest"

          # Obtener la última definición de tarea
          TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY | jq '.taskDefinition')

          # Crear una nueva definición de tarea con la nueva imagen
          NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$ECR_IMAGE_URI" \
            '{ 
              family: .family, 
              containerDefinitions: (.containerDefinitions | map(.image = $IMAGE)),
              executionRoleArn: .executionRoleArn,
              taskRoleArn: .taskRoleArn,
              networkMode: .networkMode,
              requiresCompatibilities: .requiresCompatibilities,
              cpu: .cpu,
              memory: .memory
            }'
          )

          # Registrar la nueva versión de la definición de tarea
          NEW_TASK_DEF_ARN=$(echo "$NEW_TASK_DEF" | aws ecs register-task-definition --cli-input-json file://- | jq -r '.taskDefinition.taskDefinitionArn')

          # Actualizar el servicio con la nueva versión de la tarea
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN
